-- V7: Refresh tokens for JWT session renewal (opaque tokens, hashed at rest).
-- Rotation: every refresh revokes the used token and issues a new one.
-- Reuse detection: presenting a revoked token revokes ALL tokens of that user.

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,               -- SHA-256 hex of the raw token
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,                        -- NULL = still valid
    created_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

-- Login/logout/refresh all look up by hash
CREATE INDEX idx_refresh_user_id ON refresh_tokens (user_id);
